name: api
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.0.0
  sqlite3: ^1.3.0      # direct SQLite bindings
  dotenv: ^4.2.0       # for loading your DB path & password

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
